name: docs build test
on:
  pull_request:
    branches: ["main"]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: install gustaf
        run:  python3 setup.py develop

      - name: Install dependencies
        run:  pip install -r ./docs/requirements.txt

      - name: Sphinx config
        run: |
          sphinx-apidoc -f -t docs/source/_templates -o docs/source gustaf

      - name: Sphinx build - raise error instead of warning
        run: |
          sphinx-build -b html docs/source docs/build -W
